source 'https://rubygems.org'
ruby '2.2.0'
gem 'jekyll', '~> 3.0'
gem 'jekyll-sitemap', '~> 0.9'
gem 'jekyll-gh-pages', '~> 0.1.0'
gem 'jekyll-paginate', '~> 1.1.0' 
gem 'redcarpet', '~> 3.3'
gem 'neat', '~> 1.7.2'
gem 'httparty'
gem 'slugify'
gem 'sass'
